<?xml version="1.0" encoding="UTF-8"?>
<!--
 SPDX-License-Identifier: Apache-2.0
 Originally developed by Telicent Ltd.; subsequently adapted, enhanced, and maintained by the National Digital Twin Programme.

    Copyright (c) Telicent Ltd.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.


    Modifications made by the National Digital Twin Programme (NDTP)
    © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
    and is legally attributed to the UK's Department for Business, Innovation, Science and Trade (BIST) as the governing entity.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jwt-servlet-auth-parent</artifactId>
        <groupId>uk.gov.dbt.ndtp.public</groupId>
        <version>0.90.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>jwt-servlet-auth-servlet3</artifactId>
    <name>IANode - JWT Servlet Auth - Servlet 3.x (javax.servlet)</name>
    <description>Servlet 3 implementation of JSON Web Token (JWT) authentication</description>

    <properties>
        <coverage.skip>true</coverage.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>uk.gov.dbt.ndtp.public</groupId>
            <artifactId>jwt-servlet-auth-lib</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Servlet 3.x Dependencies -->
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.dbt.ndtp.public</groupId>
            <artifactId>jwt-servlet-auth-lib</artifactId>
            <version>${project.version}</version>
            <classifier>tests</classifier>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${plugin.jacoco}</version>
            </plugin>
        </plugins>
    </build>

</project>
